- name: Create personal code directory
  ansible.builtin.file:
    path: "{{ code_dir }}"
    mode: '755'
- name: Website folder exists
  stat:
    path: "{{ code_dir }}/website"
  register: website
  tags:
    - personal 
- name: Personal Website Project
  ansible.builtin.git:
    repo: 'git@github.com:wederribas/website.git'
    dest: "{{ code_dir }}/website"
  tags:
    - personal
  when: website.stat.exists == False

