homebrew_formulas:
  - autojump
  - awscli
  - fzf
  - jq
  - neovim
  - nvm
  - pyenv
  - pyenv-virtualenv
  - tmux
  - tree
  - wget
  - zlib

homebrew_casks:
  - alfred
  - docker
  - iterm2

python_version: "3.11.4"

node_version: "--lts"