- name: Check if homebrew is already installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_folder_check
  tags:
    - homebrew
    - dotfiles
- name: Export Homebrew environment variables
  shell: |
    export HOMEBREW_NO_INSTALL_FROM_API=1
    export NONINTERACTIVE=1
- name: Install homebrew
  shell: CI=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: not homebrew_folder_check.stat.exists
  tags:
    - homebrew
    - dotfiles
- name: Install homebrew formulas
  community.general.homebrew:
    name: "{{ homebrew_formulas }}"
    state: present
  tags:
    - homebrew
    - dotfiles
- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    install_options: 'debug,appdir=/Applications'
    accept_external_apps: true
    state: present
  loop: "{{ homebrew_casks }}"
  tags:
    - homebrew
- name: Update and upgrade homebrew formulas
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags:
    - homebrew
- name: Update and upgrade homebrew casks
  community.general.homebrew_cask:
    upgrade_all: true
  tags:
    - homebrew

