- name: Check nvm is installed
  stat:
    path: /opt/homebrew/opt/nvm
  register: nvm_check
  tags:
    - nvm
- name: Install Node version {{ node_version }}
  shell: . ~/.zshrc && nvm install {{ node_version }}
  when: nvm_check.stat.exists
  args:
    executable: /bin/zsh
  tags:
    - nvm
- name: Set global Node version to {{ node_version }}
  shell: . ~/.zshrc && nvm use {{ node_version }}
  when: nvm_check.stat.exists
  args:
    executable: /bin/zsh
  tags:
    - nvm

