- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_ssh_key }}"
    dest: "{{ dest_ssh_key }}"
    mode: 0600
  tags:
    - dotfiles
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ source_ssh_key }}.pub"
    dest: "{{ dest_ssh_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - ssh

